class CodeBox_Data {
    static Init() {
        CodeBox.Themes := Map(
            "Dark", Map("Background", 0x1E1E1E, "Foreground", 0xD4D4D4, "SelectionBg", 0x264F78, "SelectionFg", 0xFFFFFF, "Comment", 0x6A9955, "String", 0xCE9178, "Keyword", 0x569CD6, "Type", 0x4EC9B0, "Number", 0xB5CEA8, "Punctuation", 0x8F8F8F, "Tag", 0x569CD6, "Attribute", 0x9CDCFE, "Error", 0xF44747, "Warning", 0xCCA700, "Value", 0xCE9178, "Key", 0x9CDCFE, "Section", 0xC586C0, "Function", 0xDCDCAA),
            "Light", Map("Background", 0xFFFFFF, "Foreground", 0x000000, "SelectionBg", 0xADD6FF, "SelectionFg", 0x000000, "Comment", 0x008000, "String", 0xA31515, "Keyword", 0x0000FF, "Type", 0x2B91AF, "Number", 0x098658, "Punctuation", 0x656565, "Tag", 0x800000, "Attribute", 0xFF0000, "Error", 0xE51400, "Warning", 0xBF8803, "Value", 0xA31515, "Key", 0x0451A5, "Section", 0x800080, "Function", 0x795E26),
            "Matrix", Map("Background", 0x050505, "Foreground", 0x00FF41, "SelectionBg", 0x004400, "SelectionFg", 0x00FF41, "Comment", 0x008F11, "String", 0x00FF41, "Keyword", 0x00FF41, "Type", 0x00FF41, "Number", 0x00FF41, "Punctuation", 0x008F11, "Tag", 0x00FF41, "Attribute", 0x00FF41, "Error", 0xFF0000, "Warning", 0xFFFF00, "Value", 0x00FF41, "Key", 0x00FF41, "Section", 0x00FF41, "Function", 0x00FF41),
            "Hacker", Map("Background", 0x000000, "Foreground", 0x00FF00, "SelectionBg", 0xAA0000, "SelectionFg", 0xFFFF00, "Comment", 0x555555, "String", 0x00AAAA, "Keyword", 0xFF0000, "Type", 0xAA00AA, "Number", 0xFFFF00, "Punctuation", 0x00FF00, "Tag", 0xFF0000, "Attribute", 0xAA00AA, "Error", 0xFFFFFF, "Warning", 0xFF00FF, "Value", 0x00AAAA, "Key", 0xFF0000, "Section", 0xFF00FF, "Function", 0xFFFF00),
            "NeonLight", Map("Background", 0xFAFAFA, "Foreground", 0x2B2B2B, "SelectionBg", 0xFFD2E6, "SelectionFg", 0x2B2B2B, "Comment", 0xA0A0A0, "String", 0xFF007F, "Keyword", 0x00A8FF, "Type", 0x9C27B0, "Number", 0xE67E22, "Punctuation", 0x4A4A4A, "Tag", 0x00A8FF, "Attribute", 0xFF007F, "Error", 0xD32F2F, "Warning", 0xFBC02D, "Value", 0xFF007F, "Key", 0x00A8FF, "Section", 0x9C27B0, "Function", 0x00E676),
            "Dracula", Map("Background", 0x282A36, "Foreground", 0xF8F8F2, "SelectionBg", 0x44475A, "SelectionFg", 0xF8F8F2, "Comment", 0x6272A4, "String", 0xF1FA8C, "Keyword", 0xFF79C6, "Type", 0x8BE9FD, "Number", 0xBD93F9, "Punctuation", 0xF8F8F2, "Tag", 0xFF79C6, "Attribute", 0x50FA7B, "Error", 0xFF5555, "Warning", 0xFFB86C, "Value", 0xF1FA8C, "Key", 0x8BE9FD, "Section", 0xBD93F9, "Function", 0x50FA7B),
            "Cyberpunk", Map("Background", 0x1A0B2E, "Foreground", 0x00FFCC, "SelectionBg", 0xFF0055, "SelectionFg", 0xFFFFFF, "Comment", 0x7B68EE, "String", 0xFFFF00, "Keyword", 0xFF00FF, "Type", 0x00FFFF, "Number", 0xFF9900, "Punctuation", 0x00FFCC, "Tag", 0xFF00FF, "Attribute", 0x00FF00, "Error", 0xFF0033, "Warning", 0xFFFF33, "Value", 0xFFFF00, "Key", 0x00FFFF, "Section", 0xFF00FF, "Function", 0xFF3366),
            "NordicFrost", Map("Background", 0xF4F7FA, "Foreground", 0x2E3440, "SelectionBg", 0xCCE0F5, "SelectionFg", 0x2E3440, "Comment", 0x7B88A1, "String", 0x5E81AC, "Keyword", 0x81A1C1, "Type", 0x88C0D0, "Number", 0xB48EAD, "Punctuation", 0x4C566A, "Tag", 0x81A1C1, "Attribute", 0x8FBCBB, "Error", 0xBF616A, "Warning", 0xD08770, "Value", 0x5E81AC, "Key", 0x81A1C1, "Section", 0xB48EAD, "Function", 0x88C0D0),
            "SunsetGlow", Map("Background", 0xFFFAF4, "Foreground", 0x3D2E2B, "SelectionBg", 0xFFE2CC, "SelectionFg", 0x3D2E2B, "Comment", 0x8A7975, "String", 0x2B9B70, "Keyword", 0xFD5E53, "Type", 0x9E5A9D, "Number", 0xFE9A22, "Punctuation", 0x5C4A47, "Tag", 0xFD5E53, "Attribute", 0x9E5A9D, "Error", 0xE53935, "Warning", 0xFFB300, "Value", 0x2B9B70, "Key", 0xFD5E53, "Section", 0x9E5A9D, "Function", 0x10B981),
            "CandyStore", Map("Background", 0xFFF0F5, "Foreground", 0x4A3E4D, "SelectionBg", 0xFFD1E8, "SelectionFg", 0x4A3E4D, "Comment", 0x9A8E9C, "String", 0x00B0FF, "Keyword", 0xFF4081, "Type", 0x7C4DFF, "Number", 0xFFAB40, "Punctuation", 0x6E5F70, "Tag", 0xFF4081, "Attribute", 0x7C4DFF, "Error", 0xFF1744, "Warning", 0xFFEA00, "Value", 0x00B0FF, "Key", 0x7C4DFF, "Section", 0xFF4081, "Function", 0x00E676)
        )

        CodeBox.Syntaxes := Map(
            "ahk2", [{ p: "[\{\}\(\)\[\]\.,;:+\-*/!%&|<>=\?]", c: "Punctuation" }, { p: "\b(0x[0-9a-fA-F]+|\d+(\.\d+)?)\b", c: "Number" }, { p: "\b(if|else|loop|while|for|return|class|static|global|local|try|catch|finally|break|continue|throw)\b", c: "Keyword", b: true }, { p: "\b(true|false|unset|null)\b", c: "Keyword" }, { p: "\b(A_[A-Za-z0-9_]+)\b", c: "Type", b: true }, { p: "\b(MsgBox|Run|StrReplace|RegExMatch|RegExReplace|Map|Array|Buffer|DllCall|SendMessage|PostMessage|InStr|SubStr)\b", c: "Function" }, { p: "\b(?!(?:if|while|for|loop|return|catch|and|or|in|is)\b)[A-Za-z0-9_]+\s+\(", c: "Error", u: 8, msg: "Space between function name and parenthesis is not allowed in AutoHotkey v2." }, { p: "%[A-Za-z0-9_]+%", c: "Error", u: 8, msg: "Legacy AHK v1 variable dereferencing is not supported in v2." }, { p: "===", c: "Error", u: 8, msg: "Invalid operator. AutoHotkey v2 uses '==' for case-sensitive comparison." }, { p: "\b(?:MsgBox|Send|Run|WinWait|WinActivate),\s", c: "Warning", u: 8, msg: "AHK v1 command syntax found. AHK v2 requires function call syntax." }, { p: "(?mi)^([ \t]*)(?:return|break|continue|throw|ExitApp)\b[^\n]*\n+(?:[ \t]*\n)*\1[ \t]*\K(?![}#]|catch\b|finally\b|else\b|case\b|default\b|[\w^!+#]+::|[\w]+:).+", c: "Warning", u: 8, msg: "Unreachable code detected. Execution will not reach this line." }, { p: '(?m)".*?"', c: "String" }, { p: "(?m)'.*?'", c: "String" }, { p: "(?m)(^|[ \t]);.*", c: "Comment" }, { p: "(?s)/\*.*?\*/", c: "Comment" }],
            "cs", [{ p: "[\{\}\(\)\[\]<>\.,;:+\-*/!%&|=\?]", c: "Punctuation" }, { p: "\b\d+(\.\d+)?\b", c: "Number" }, { p: "\b(string|int|bool|var|object|double|float|long|Exception|void|char|byte|short|decimal)\b", c: "Type", b: true }, { p: "\b(if|else|while|for|foreach|return|class|static|public|private|protected|async|await|try|catch|using|namespace|new|override|virtual)\b", c: "Keyword", b: true }, { p: "\b(true|false|null)\b", c: "Keyword" }, { p: "\b(class|static|void|public|private)\s*=", c: "Error", u: 8, msg: "Reserved keyword cannot be used as a variable name or assigned a value." }, { p: "(?mi)^([ \t]*)(?:return|break|continue|throw)\b[^\n]*\n+(?:[ \t]*\n)*\1[ \t]*\K(?![}#]|catch\b|finally\b|else\b|case\b|default\b).+", c: "Warning", u: 8, msg: "Unreachable code detected. Execution will not reach this line." }, { p: '(?m)".*?"', c: "String" }, { p: "(?m)//.*", c: "Comment" }, { p: "(?s)/\*.*?\*/", c: "Comment" }],
            "js", [{ p: "[\{\}\(\)\[\]<>\.,;:+\-*/!%&|=\?]", c: "Punctuation" }, { p: "\b\d+(\.\d+)?\b", c: "Number" }, { p: "\b(console|window|document|Math|JSON|Promise|Array|Object|String|Number)\b", c: "Type" }, { p: "\b(let|const|var|function|return|if|else|while|for|of|in|class|extends|constructor|new|try|catch|finally|async|await|import|export|from|default|switch|case|break)\b", c: "Keyword", b: true }, { p: "\b(true|false|null|undefined)\b", c: "Keyword" }, { p: "\b(log|warn|error|setTimeout|setInterval|fetch|then|catch|map|filter|reduce)\b", c: "Function" }, { p: "==(?!=)", c: "Warning", u: 8, msg: "Use strict equality '===' to avoid type coercion bugs." }, { p: ",\s*(?=\})", c: "Warning", u: 8, msg: "Trailing commas in objects can cause issues in older JavaScript engines." }, { p: "(?mi)^([ \t]*)(?:return|break|continue|throw)\b[^\n]*\n+(?:[ \t]*\n)*\1[ \t]*\K(?![}#]|catch\b|finally\b|else\b|case\b|default\b).+", c: "Warning", u: 8, msg: "Unreachable code detected. Execution will not reach this line." }, { p: '(?m)".*?"', c: "String" }, { p: "(?m)'.*?'", c: "String" }, { p: "(?s)``.*?``", c: "String" }, { p: "(?m)//.*", c: "Comment" }, { p: "(?s)/\*.*?\*/", c: "Comment" }],
            "python", [{ p: "[\{\}\(\)\[\]<>\.,;:+\-*/!%&|=\?]", c: "Punctuation" }, { p: "\b\d+(\.\d+)?\b", c: "Number" }, { p: "\b(str|int|bool|float|list|dict|set|tuple|print|len|range|enumerate|zip|type|open|dir|getattr|setattr|hasattr)\b", c: "Function" }, { p: "\b(def|class|return|if|elif|else|while|for|in|try|except|finally|with|as|import|from|pass|break|continue|lambda|yield|global|nonlocal|async|await)\b", c: "Keyword", b: true }, { p: "\b(True|False|None)\b", c: "Keyword" }, { p: "\bprint\s+[\x22'\[a-zA-Z0-9]", c: "Error", u: 8, msg: "Python 2 print statement found. Python 3 requires print() as a function call." }, { p: "(?mi)^([ \t]*)(?:return|break|continue|raise)\b[^\n]*\n+(?:[ \t]*\n)*\1[ \t]*\K(?![}#]|except\b|finally\b|elif\b|else\b).+", c: "Warning", u: 8, msg: "Unreachable code detected. Execution will not reach this line." }, { p: '(?s)""".*?"""', c: "String" }, { p: "(?s)'''.*?'''", c: "String" }, { p: '(?m)".*?"', c: "String" }, { p: "(?m)'.*?'", c: "String" }, { p: "(?m)#.*", c: "Comment" }],
            "xml", [{ p: "<\/?[\w:\-]+", c: "Tag", b: true }, { p: "\/?>", c: "Tag", b: true }, { p: "\b[\w:\-]+(?=\s*\=)", c: "Attribute" }, { p: '(?m)".*?"', c: "String" }, { p: "(?s)<!--.*?-->", c: "Comment" }],
            "json", [{ p: "[\{\}\[\]:,]", c: "Punctuation" }, { p: "\b\d+(\.\d+)?\b", c: "Number" }, { p: "\b(true|false|null)\b", c: "Keyword" }, { p: ",\s*(?=[\]\}])", c: "Error", u: 8, msg: "Trailing commas are strictly prohibited in JSON standard." }, { p: '(?m)".*?"(?=\s*:)', c: "Key", b: true }, { p: '(?m)".*?"(?!\s*:)', c: "String" }],
            "ini", [{ p: "=", c: "Punctuation" }, { p: "(?m)^[\w\s\.\-]+(?=\=)", c: "Key" }, { p: "(?m)=\s*\K.*", c: "Value" }, { p: "(?m)^\[.*?\]", c: "Section", b: true }, { p: "(?m)^[;#].*", c: "Comment" }],
            "css", [{ p: "[\{\}\(\)\[\]\.,;:+\-*/!%&|=\?]", c: "Punctuation" }, { p: "(?m)^[\s]*[\w\-\.:#]+(?=\s*\{)", c: "Tag", b: true }, { p: "\b[\w-]+(?=\s*:)", c: "Attribute" }, { p: "\b\d+(\.\d+)?(px|em|rem|vh|vw|%|pt)?\b", c: "Number" }, { p: ":\s*;", c: "Error", u: 8, msg: "Missing property value before semicolon." }, { p: '(?m)".*?"', c: "String" }, { p: "(?m)'.*?'", c: "String" }, { p: "(?s)/\*.*?\*/", c: "Comment" }],
            "csv", [{ p: ",", c: "Punctuation" }, { p: "\b\d+(\.\d+)?\b", c: "Number" }, { p: '(?m)".*?"', c: "String" }],
            "tsv", [{ p: "\t", c: "Punctuation" }, { p: "\b\d+(\.\d+)?\b", c: "Number" }, { p: '(?m)".*?"', c: "String" }],
            "plain", []
        )
    }
}
